<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
		<OutputType>Library</OutputType>
		<PlatformTarget>x64</PlatformTarget>
		<RootNamespace>ModProject</RootNamespace>
		<AssemblyName>ModProject</AssemblyName>
		<OutputPath>bin\Debug\</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="System" />
		<Reference Include="System.Core" />
		<Reference Include="MelonLoader">
			<HintPath>References\MelonLoader.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>References\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<HintPath>References\Assembly-CSharp.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Compile Include="ModMain.cs"/>
	</ItemGroup>

	<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>